FROM node:9.11.2

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./bike-along/package.json /usr/src/app/package.json
COPY ./bike-along/yarn.lock /usr/src/app/yarn.lock
RUN yarn install

EXPOSE 3000

CMD ["yarn", "start"]