version: '2'
services:
  frontend:
    build: ./frontend/
    ports:
      - 0.0.0.0:80:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/bike-along:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  api:
    build: ./backend/
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:443:443
    volumes:
      - ./backend/app:/app
